import { EXAMPLE_COMPONENT_NAME } from '../registry/frameworks';
import type { GenerationContext } from '../registry/pluginTypes';
import type { FileOp } from '../types';
import { skillFileOps } from './skillFiles';

/** Directory (relative to target root) the sample files are written into. */
export const EXAMPLE_DIR = 'atomic-testing-example';

function scenePartFile(ctx: GenerationContext): FileOp {
  const note = ctx.designSystem.usageNote ? `\n// ${ctx.designSystem.usageNote}` : '';
  return {
    path: `${EXAMPLE_DIR}/scenePart.ts`,
    kind: 'scene-part',
    contents: `import { byDataTestId } from '@atomic-testing/core';
import type { ScenePart } from '@atomic-testing/core';
import { HTMLTextInputDriver } from '@atomic-testing/component-driver-html';

// A scene part maps named parts to a (locator, driver) pair. This starter uses
// the framework-agnostic HTML text-input driver against a plain <input>.${note}
export const scenePart = {
  field: { locator: byDataTestId('example-input'), driver: HTMLTextInputDriver },
} satisfies ScenePart;
`,
  };
}

function unitTestFile(ctx: GenerationContext): FileOp {
  const engine = ctx.framework.exampleEngine(ctx);
  if (!engine) {
    throw new Error(`Framework ${ctx.framework.id} has no example engine; this combination should be disabled.`);
  }
  const importLines = [
    `import type { TestEngine } from '@atomic-testing/core';`,
    ...engine.imports,
    `import { scenePart } from './scenePart';`,
  ];
  const beforeEach = engine.isAsync
    ? `  beforeEach(async () => {\n    engine = ${engine.engineExpr};\n  });`
    : `  beforeEach(() => {\n    engine = ${engine.engineExpr};\n  });`;

  return {
    path: `${EXAMPLE_DIR}/${ctx.runner.testFileName(ctx)}`,
    kind: 'example-test',
    contents: `${importLines.join('\n')}

// Sample test generated by create-atomic-testing — it should be green on the
// first run. Replace it with tests for your own components.
describe('${EXAMPLE_COMPONENT_NAME}', () => {
  let engine: TestEngine<typeof scenePart>;

${beforeEach}

  afterEach(() => engine.cleanUp());

  it('reads back the value it sets', async () => {
    await engine.parts.field.setValue('hello atomic-testing');
    expect(await engine.parts.field.getValue()).toBe('hello atomic-testing');
  });
});
`,
  };
}

function playwrightTestFile(ctx: GenerationContext): FileOp {
  return {
    path: `${EXAMPLE_DIR}/${ctx.runner.testFileName(ctx)}`,
    kind: 'example-test',
    contents: `import { expect, test } from '@playwright/test';

// EXPERIMENTAL starter. atomic-testing's Playwright flow drives your real,
// running app through PlaywrightInteractor + a scene part. Point baseURL at your
// dev server in playwright.config.ts, then build the scene against your pages.
// See https://atomic-testing.dev for the full setup.
test('example page loads', async ({ page }) => {
  await page.goto('/');
  await expect(page).toHaveURL(/.*/);
});
`,
  };
}

/**
 * Produce every file for a recipe from the composed plugins. Pure — returns
 * file operations; nothing touches disk. For the Playwright (e2e) harness there
 * is no in-process component/scene, so only the config + a starter e2e are emitted.
 */
export function generateFiles(ctx: GenerationContext): FileOp[] {
  const config = ctx.runner.configFile(ctx);

  if (ctx.runner.harness === 'playwright') {
    return [config, playwrightTestFile(ctx), ...skillFileOps(ctx)];
  }

  const component = ctx.framework.exampleComponent(ctx);
  if (!component) {
    throw new Error(`Framework ${ctx.framework.id} has no example component; this combination should be disabled.`);
  }

  return [
    config,
    ...(ctx.runner.extraFiles?.(ctx) ?? []),
    { path: `${EXAMPLE_DIR}/${component.fileName}`, kind: 'example-component', contents: component.source },
    scenePartFile(ctx),
    unitTestFile(ctx),
    ...skillFileOps(ctx),
  ];
}
