import { THIRD_PARTY } from '../constants';
import type { DependencySpec, FrameworkId } from '../types';
import type { FrameworkPlugin } from './pluginTypes';

/** Symbol name used for the generated example component across all frameworks. */
const COMPONENT = 'ExampleComponent';

/** The two import lines every framework's example test needs (engine + component). */
const engineImports = (engine: string): string[] => [
  `import { createTestEngine } from '@atomic-testing/${engine}';`,
  `import { ${COMPONENT} } from './${COMPONENT}';`,
];

const reactRuntime = (major: number): DependencySpec[] => {
  if (major >= 19) {
    return [
      THIRD_PARTY.react19,
      THIRD_PARTY.reactDom19,
      THIRD_PARTY.typesReact19,
      THIRD_PARTY.typesReactDom19,
      THIRD_PARTY.tlReact,
      THIRD_PARTY.tlDom,
      THIRD_PARTY.tlUserEvent,
    ];
  }
  if (major === 18) {
    return [
      THIRD_PARTY.react18,
      THIRD_PARTY.reactDom18,
      THIRD_PARTY.typesReact18,
      THIRD_PARTY.typesReactDom18,
      THIRD_PARTY.tlReact,
      THIRD_PARTY.tlDom,
      THIRD_PARTY.tlUserEvent,
    ];
  }
  // legacy 16/17 — deliberately without @testing-library/react (ADR: keeps the
  // legacy path off the RTL graph).
  return [
    THIRD_PARTY.react17,
    THIRD_PARTY.reactDom17,
    THIRD_PARTY.typesReact17,
    THIRD_PARTY.typesReactDom17,
    THIRD_PARTY.tlDom,
    THIRD_PARTY.tlUserEvent,
  ];
};

const reactFramework: FrameworkPlugin = {
  id: 'react',
  displayName: 'React',
  supportedMajors: [16, 17, 18, 19],
  defaultRunner: 'jest',
  enginePackage(major) {
    if (major >= 19) return 'react-19';
    if (major === 18) return 'react-18';
    if (major === 16 || major === 17) return 'react-legacy';
    return null;
  },
  runtimeDeps: reactRuntime,
  // SWC's automatic JSX runtime for .tsx, and IS_REACT_ACT_ENVIRONMENT so the
  // ReactInteractor's act()-wrapped updates flush. These are React facts, owned
  // here rather than special-cased inside the jest runner.
  jestTransform: `['@swc/jest', { jsc: { transform: { react: { runtime: 'automatic' } } } }]`,
  jestGlobals: { IS_REACT_ACT_ENVIRONMENT: true },
  exampleComponent() {
    return {
      fileName: `${COMPONENT}.tsx`,
      source: `// Sample component generated by create-atomic-testing.
// Replace it with your own component once the example test is green.
export function ${COMPONENT}() {
  return (
    <label>
      Example field
      <input data-testid="example-input" defaultValue="" />
    </label>
  );
}
`,
    };
  },
  exampleEngine(ctx) {
    const engine = ctx.framework.enginePackage(ctx.selection.frameworkMajor);
    return {
      imports: engineImports(engine as string),
      engineExpr: `createTestEngine(<${COMPONENT} />, scenePart)`,
      isAsync: false,
    };
  },
};

const vueFramework: FrameworkPlugin = {
  id: 'vue',
  displayName: 'Vue 3',
  supportedMajors: [3],
  defaultRunner: 'jest',
  enginePackage(major) {
    return major === 3 ? 'vue-3' : null;
  },
  runtimeDeps() {
    return [THIRD_PARTY.vue, THIRD_PARTY.vueCompilerSfc, THIRD_PARTY.tlVue, THIRD_PARTY.tlDom, THIRD_PARTY.tlUserEvent];
  },
  // Vue's jsdom leg must resolve the Node export condition, or @testing-library/
  // vue pulls a build that throws at load. jsdom-mode Vitest needs the Vue plugin.
  jestEnvironmentOptions: { customExportConditions: ['node', 'node-addons'] },
  vitePlugin: {
    importLine: `import vue from '@vitejs/plugin-vue';`,
    pluginExpr: 'vue()',
    dep: THIRD_PARTY.vitePluginVue,
  },
  exampleComponent() {
    return {
      // Defined as a render function (not an .vue SFC) so the example needs no
      // SFC/template-compiler transform — plain @swc/jest handles it.
      fileName: `${COMPONENT}.ts`,
      source: `import { defineComponent, h } from 'vue';

// Sample component generated by create-atomic-testing.
// Replace it with your own component once the example test is green.
export const ${COMPONENT} = defineComponent({
  name: '${COMPONENT}',
  setup() {
    return () => h('label', ['Example field', h('input', { 'data-testid': 'example-input' })]);
  },
});
`,
    };
  },
  exampleEngine(ctx) {
    const engine = ctx.framework.enginePackage(ctx.selection.frameworkMajor);
    return {
      imports: engineImports(engine as string),
      engineExpr: `createTestEngine(${COMPONENT}, scenePart)`,
      isAsync: false,
    };
  },
};

const angularRuntime = (major: number): DependencySpec[] => {
  const ng = (name: string): DependencySpec => ({ name, range: `^${major}.0.0` });
  return [
    ng('@angular/common'),
    ng('@angular/compiler'),
    ng('@angular/core'),
    ng('@angular/platform-browser'),
    THIRD_PARTY.zoneJs,
    THIRD_PARTY.rxjs,
  ];
};

const angularFramework: FrameworkPlugin = {
  id: 'angular',
  displayName: 'Angular',
  supportedMajors: [20, 21, 22],
  // Angular's proven path in this repo is Vitest browser mode (ADR-013); there
  // is no Jest fixture, so Jest is registered-but-disabled in the matrix.
  defaultRunner: 'vitest-browser',
  enginePackage(major) {
    return major >= 20 && major <= 22 ? `angular-${major}` : null;
  },
  runtimeDeps: angularRuntime,
  // Angular browser-mode needs zone.js + the JIT compiler bootstrapped in a
  // setup file; that fact lives here, not special-cased in the vitest runner.
  vitestBrowserSetup: {
    setupFile: {
      path: 'atomic-testing-example/vitest.setup.ts',
      kind: 'setup',
      contents: `// Angular browser-mode test setup.\nimport '@angular/compiler';\nimport 'zone.js';\n`,
    },
    note: `// Angular browser-mode ALSO needs a Vite Angular plugin (e.g. @analogjs/vite-plugin-angular)\n// added to \`plugins\` to compile components — this config is a starting point.`,
  },
  exampleComponent() {
    return {
      fileName: `${COMPONENT}.ts`,
      source: `import { Component } from '@angular/core';

// Sample component generated by create-atomic-testing.
// Replace it with your own component once the example test is green.
@Component({
  selector: 'app-example',
  standalone: true,
  template: '<label>Example field<input data-testid="example-input" /></label>',
})
export class ${COMPONENT} {}
`,
    };
  },
  exampleEngine(ctx) {
    const engine = ctx.framework.enginePackage(ctx.selection.frameworkMajor);
    return {
      imports: engineImports(engine as string),
      // Angular's createTestEngine is async (bootstraps a standalone component).
      engineExpr: `await createTestEngine(${COMPONENT}, scenePart)`,
      isAsync: true,
    };
  },
};

const noneFramework: FrameworkPlugin = {
  id: 'none',
  displayName: 'None / vanilla DOM',
  supportedMajors: [],
  defaultRunner: 'jest',
  enginePackage() {
    return null;
  },
  runtimeDeps() {
    return [];
  },
  // No per-framework TestEngine ships for vanilla DOM yet, so vanilla recipes
  // stay disabled in the matrix. The plugin exists so detection can name it.
  exampleComponent() {
    return null;
  },
  exampleEngine() {
    return null;
  },
};

export const FRAMEWORKS: Readonly<Record<FrameworkId, FrameworkPlugin>> = {
  react: reactFramework,
  vue: vueFramework,
  angular: angularFramework,
  none: noneFramework,
};

export function getFramework(id: FrameworkId): FrameworkPlugin {
  return FRAMEWORKS[id];
}

export { COMPONENT as EXAMPLE_COMPONENT_NAME };
