import { THIRD_PARTY } from '../constants';
import { execCommand } from '../install/packageManager';
import type { FileOp, RunnerId } from '../types';
import { EXAMPLE_COMPONENT_NAME } from './frameworks';
import type { GenerationContext, RunnerPlugin } from './pluginTypes';

const jestConfig = (ctx: GenerationContext): FileOp => {
  const isReact = ctx.framework.id === 'react';
  const transform = isReact
    ? `    '^.+\\\\.(t|j)sx?$': ['@swc/jest', { jsc: { transform: { react: { runtime: 'automatic' } } } }],`
    : `    '^.+\\\\.(t|j)sx?$': '@swc/jest',`;
  // IS_REACT_ACT_ENVIRONMENT tells React 18/19 it is inside act(); required for
  // the ReactInteractor to flush updates. Vue/others must NOT set it.
  const globals = isReact ? `\n  globals: {\n    IS_REACT_ACT_ENVIRONMENT: true,\n  },` : '';
  return {
    path: 'jest.config.cjs',
    kind: 'runner-config',
    contents: `// Standalone Jest config generated by create-atomic-testing.
/** @type {import('jest').Config} */
module.exports = {
  testEnvironment: 'jsdom',
  transform: {
${transform}
  },
  testMatch: ['**/*.test.@(ts|tsx|js|jsx)'],${globals}
};
`,
  };
};

const jestRunner: RunnerPlugin = {
  id: 'jest',
  displayName: 'Jest (jsdom)',
  harness: 'unit',
  deps() {
    return [
      THIRD_PARTY.jest,
      THIRD_PARTY.jestEnvJsdom,
      THIRD_PARTY.swcJest,
      THIRD_PARTY.swcCore,
      THIRD_PARTY.typesJest,
      THIRD_PARTY.typescript,
    ];
  },
  configFile: jestConfig,
  scripts() {
    return { test: 'jest' };
  },
  nextSteps(ctx) {
    return [execCommand(ctx.selection.packageManager, 'jest')];
  },
  testFileName(ctx) {
    return `${EXAMPLE_COMPONENT_NAME}.test.${ctx.ext.test}`;
  },
};

const vitestConfig = (ctx: GenerationContext): FileOp => {
  const vuePlugin = ctx.framework.id === 'vue';
  const pluginImport = vuePlugin ? `import vue from '@vitejs/plugin-vue';\n` : '';
  const plugins = vuePlugin ? '\n  plugins: [vue()],' : '';
  return {
    path: 'vitest.config.ts',
    kind: 'runner-config',
    contents: `// Standalone Vitest config generated by create-atomic-testing.
import { defineConfig } from 'vitest/config';
${pluginImport}
export default defineConfig({${plugins}
  test: {
    environment: 'jsdom',
    globals: true,
  },
});
`,
  };
};

const vitestRunner: RunnerPlugin = {
  id: 'vitest',
  displayName: 'Vitest (jsdom)',
  harness: 'unit',
  deps(ctx) {
    const base = [THIRD_PARTY.vitest, THIRD_PARTY.jsdom, THIRD_PARTY.typescript];
    return ctx.framework.id === 'vue' ? [...base, THIRD_PARTY.vitePluginVue] : base;
  },
  configFile: vitestConfig,
  scripts() {
    return { test: 'vitest run' };
  },
  nextSteps(ctx) {
    return [execCommand(ctx.selection.packageManager, 'vitest', 'run')];
  },
  testFileName(ctx) {
    return `${EXAMPLE_COMPONENT_NAME}.test.${ctx.ext.test}`;
  },
};

const vitestBrowserConfig = (): FileOp => ({
  path: 'vitest.config.ts',
  kind: 'runner-config',
  contents: `// Standalone Vitest (browser mode) config generated by create-atomic-testing.
// EXPERIMENTAL: browser-mode setup — especially for Angular — usually needs a
// framework Vite plugin. See https://atomic-testing.dev for the reference setup.
import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    globals: true,
    browser: {
      enabled: true,
      provider: 'playwright',
      instances: [{ browser: 'chromium' }],
    },
  },
});
`,
});

const vitestBrowserRunner: RunnerPlugin = {
  id: 'vitest-browser',
  displayName: 'Vitest (browser mode + Playwright)',
  harness: 'unit',
  deps() {
    return [THIRD_PARTY.vitest, THIRD_PARTY.vitestBrowserPlaywright, THIRD_PARTY.playwright, THIRD_PARTY.typescript];
  },
  configFile: vitestBrowserConfig,
  scripts() {
    return { test: 'vitest run' };
  },
  nextSteps(ctx) {
    return [
      execCommand(ctx.selection.packageManager, 'playwright', 'install chromium --with-deps'),
      execCommand(ctx.selection.packageManager, 'vitest', 'run'),
    ];
  },
  testFileName(ctx) {
    return `${EXAMPLE_COMPONENT_NAME}.browser.test.${ctx.ext.test}`;
  },
};

const playwrightConfig = (): FileOp => ({
  path: 'playwright.config.ts',
  kind: 'runner-config',
  contents: `// Standalone Playwright config generated by create-atomic-testing.
import { defineConfig } from '@playwright/test';

export default defineConfig({
  testMatch: '**/*.e2e.@(ts|tsx)',
  use: {
    // Point this at your app's dev server; Playwright drives a real browser.
    baseURL: 'http://localhost:3000',
  },
  // webServer: { command: 'npm run dev', url: 'http://localhost:3000', reuseExistingServer: true },
});
`,
});

const playwrightRunner: RunnerPlugin = {
  id: 'playwright',
  displayName: 'Playwright (e2e, real browser)',
  harness: 'playwright',
  deps() {
    return [THIRD_PARTY.playwrightTest, THIRD_PARTY.typescript];
  },
  configFile: playwrightConfig,
  scripts() {
    return { 'test:e2e': 'playwright test' };
  },
  nextSteps(ctx) {
    return [
      execCommand(ctx.selection.packageManager, 'playwright', 'install --with-deps'),
      execCommand(ctx.selection.packageManager, 'playwright', 'test'),
    ];
  },
  testFileName(ctx) {
    return `${EXAMPLE_COMPONENT_NAME}.e2e.${ctx.ext.test}`;
  },
};

export const RUNNERS: Readonly<Record<RunnerId, RunnerPlugin>> = {
  jest: jestRunner,
  vitest: vitestRunner,
  'vitest-browser': vitestBrowserRunner,
  playwright: playwrightRunner,
};

export function getRunner(id: RunnerId): RunnerPlugin {
  return RUNNERS[id];
}
