# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
name: 'Setup dependencies only'
description: 'Setup Node.js, PNPM and install dependencies without building'

runs:
  using: 'composite'
  steps:
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: PNPM Setup
      uses: pnpm/action-setup@v4
      with:
        version: 10
        run_install: false

    - name: Install dependencies
      shell: bash
      run: pnpm install --no-frozen-lockfile
