// Pure renderer for the scaffolder's embedded copy of the four testing skills.
//
// create-atomic-testing must be able to drop the SKILL.md files into a
// newly-scaffolded project, but its generation layer is pure (no fs at emit
// time) and the published npm package does not ship `.claude/skills/`. So the
// skill bodies are embedded as a committed, generated TypeScript constant —
// derived from `.claude/skills/*/SKILL.md`, never hand-maintained (the same
// "derived, not hand-written" discipline as ATOMIC_VERSION).
//
// This module is the single source of that derivation: gen-skill-content.mjs
// writes the module, and check-skill-sync.mjs re-renders it to detect drift.
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * The four skills, in the fixed order they are embedded. They form a lifecycle
 * (scaffold → author → diagnose → sync) and cross-reference each other by name,
 * so all four are always emitted together — never a subset.
 */
export const SKILL_IDS = [
  'scaffold-test-driver',
  'author-component-tests',
  'diagnose-test-failure',
  'sync-test-driver',
];

/** Path, relative to the package, of the generated module this renderer feeds. */
export const GENERATED_MODULE_REL = 'packages/create-atomic-testing/src/generate/skillContent.generated.ts';

/**
 * Read the four SKILL.md bodies from a skills directory.
 * @param {string} skillsDir absolute path to `.claude/skills`
 * @returns {{ id: string, targetPath: string, contents: string }[]}
 */
export function readSkillFiles(skillsDir) {
  return SKILL_IDS.map(id => ({
    id,
    targetPath: `.claude/skills/${id}/SKILL.md`,
    contents: readFileSync(join(skillsDir, id, 'SKILL.md'), 'utf8'),
  }));
}

const HEADER = `// @generated by scripts/skills/gen-skill-content.mjs — DO NOT EDIT BY HAND.
// Source of truth: .claude/skills/<id>/SKILL.md. Regenerate & commit with:
//   pnpm gen:skill-content
// Drift between this file and the source skills is caught by \`pnpm check:skill-sync\`.
//
// The four adopter-facing testing skills, embedded verbatim so the scaffolder can
// write them into a project without reading the filesystem at generation time
// (generation stays pure; the published package does not ship .claude/skills/).`;

/**
 * Render the committed generated module from the current skill sources.
 * Deterministic: the same inputs always produce byte-identical output, so the
 * freshness check can compare exactly.
 * @param {string} skillsDir absolute path to `.claude/skills`
 * @returns {string}
 */
export function renderSkillContentModule(skillsDir) {
  const skills = readSkillFiles(skillsDir);
  const entries = skills
    .map(
      s =>
        `  {\n    id: ${JSON.stringify(s.id)},\n    targetPath: ${JSON.stringify(s.targetPath)},\n    contents: ${JSON.stringify(s.contents)},\n  },`
    )
    .join('\n');
  return `${HEADER}

export interface EmbeddedSkill {
  readonly id: string;
  readonly targetPath: string;
  readonly contents: string;
}

export const EMBEDDED_SKILLS: readonly EmbeddedSkill[] = [
${entries}
];
`;
}
