import path from 'path';

// @ts-check
// Note: type annotations allow type checking and IDEs autocompletion
// require('prism-react-renderer/themes/github');
import type * as Preset from '@docusaurus/preset-classic';
import type { Config } from '@docusaurus/types';
import type { PrismTheme } from 'prism-react-renderer';

import { classifyPackage, getDocPackageNames } from './scripts/docPackages.mjs';

// Custom Prism theme: code blocks are always dark navy with the design's token colors,
// in both light and dark site themes. Colors mirror the design tokenizer palette.
const atomicCodeTheme: PrismTheme = {
  plain: { color: '#cbd7e6', backgroundColor: '#0e1726' },
  styles: [
    { types: ['comment', 'prolog', 'doctype', 'cdata'], style: { color: '#5e7488', fontStyle: 'italic' } },
    { types: ['punctuation'], style: { color: '#7e91ab' } },
    { types: ['operator', 'entity', 'url'], style: { color: '#9fb3cc' } },
    { types: ['keyword', 'storage', 'keyword-control', 'atrule'], style: { color: '#c9a6f0' } },
    { types: ['boolean', 'number', 'constant', 'symbol', 'inserted'], style: { color: '#5fe3c8' } },
    { types: ['string', 'char', 'attr-value'], style: { color: '#7fd1f0' } },
    { types: ['function', 'function-variable'], style: { color: '#7fd1f0' } },
    { types: ['class-name', 'maybe-class-name', 'builtin'], style: { color: '#8fd4ff' } },
    { types: ['tag', 'deleted'], style: { color: '#7fb0f5' } },
    { types: ['attr-name', 'property', 'selector'], style: { color: '#9bd0ff' } },
    { types: ['variable', 'parameter'], style: { color: '#cbd7e6' } },
    { types: ['regex', 'important'], style: { color: '#5fe3c8' } },
    { types: ['namespace'], style: { opacity: '0.7' } },
  ],
};

// Applies a reader's persisted sidebar width BEFORE first paint so the sidebar
// doesn't flash from the stock 300px to the saved value after hydration. The
// clamp range must match DocSidebarResizer's MIN/MAX (see src/theme/DocSidebarResizer).
function sidebarWidthInitPlugin() {
  return {
    name: 'sidebar-width-init',
    injectHtmlTags() {
      return {
        headTags: [
          {
            tagName: 'script',
            innerHTML: [
              '(function(){try{',
              "var w=localStorage.getItem('docSidebarWidth');",
              'if(w){var n=parseInt(w,10);',
              // Clamp (not range-check) so an out-of-range stored value is still
              // applied pre-paint, matching DocSidebarResizer.clampWidth() — a
              // range-check would skip it and let the component reintroduce a flash.
              'if(!isNaN(n)){n=Math.max(200,Math.min(480,n));',
              "document.documentElement.style.setProperty('--doc-sidebar-width',n+'px');}}",
              '}catch(e){}})();',
            ].join(''),
          },
        ],
      };
    },
  };
}

function getPackageEntryPoints() {
  return getDocPackageNames().map(name => `../packages/${name}`);
}

// ── API sidebar shaping ────────────────────────────────────────────────────
// TypeDoc emits each package as a folder of per-kind subfolders (classes/,
// interfaces/, variables/, …), which Docusaurus's autogenerated sidebar mirrors
// verbatim: lowercase kind categories, and doc labels carrying TypeDoc's kind
// prefix + MDX-escaped generics ("Abstract Class: ComponentDriver\<T\>"). Left
// alone, a bucket becomes one long flat run once you also flatten those kinds.
// Instead we wrap each package as ONE collapsed category (linked to its landing
// page) and shape its interior by how the package reads — see shapeApiPackage.

// Docusaurus labels the kind folders with these lowercase names (no _category_.json,
// so no title-casing) — confirmed against generated sidebar HTML. Map to display
// labels; a package rarely has all of them.
const KIND_DISPLAY: Record<string, string> = {
  classes: 'Classes',
  interfaces: 'Interfaces',
  'type aliases': 'Type Aliases',
  'type-aliases': 'Type Aliases',
  variables: 'Variables',
  functions: 'Functions',
  enumerations: 'Enumerations',
  namespaces: 'Namespaces',
};
// Deterministic display order for kind subcategories. Framework packages lead
// with Classes (the Interactor/engine you came for); driver packages flatten
// Classes out entirely, so only the tail applies there.
const FRAMEWORK_KIND_ORDER = [
  'Classes',
  'Functions',
  'Interfaces',
  'Type Aliases',
  'Variables',
  'Enumerations',
  'Namespaces',
];
const DRIVER_NONCLASS_ORDER = ['Interfaces', 'Type Aliases', 'Variables', 'Functions', 'Enumerations', 'Namespaces'];

const kindDisplay = (label: unknown): string | null =>
  typeof label === 'string' ? (KIND_DISPLAY[label.toLowerCase()] ?? null) : null;

// Drop TypeDoc's kind prefix and undo MDX backslash-escaping, so a generic class
// reads "ComponentDriver<T>" in the nav rather than "Abstract Class: ComponentDriver\<T\>".
function cleanLabel(raw: string): string {
  return raw
    .replace(/^\s*(?:Abstract\s+)?(?:Class|Interface|Type Alias|Variable|Function|Enumeration|Enum|Namespace):\s*/i, '')
    .replace(/\\([<>_*`|~])/g, '$1')
    .trim();
}

function sortByKindOrder(cats: any[], order: string[]): any[] {
  const rank = (c: any) => {
    const i = order.indexOf(c.label);
    return i === -1 ? order.length : i;
  };
  return [...cats].sort((a, b) => rank(a) - rank(b));
}

// Reshape one `api/<name>` package's autogenerated items into a single collapsed
// package category. Interior differs by bucket (docPackages.classifyPackage):
//   - driver:    supporting kinds as collapsed subcategories, then driver classes flat
//   - framework: every kind (Classes included) grouped into its own subcategory
function shapeApiPackage(name: string, items: any[], docs: any[]): any | null {
  const docsById = new Map((docs ?? []).map(d => [d.id, d]));
  const labelOf = (it: any): string => {
    const meta = docsById.get(it.id);
    const raw = it.label ?? meta?.frontMatter?.sidebar_label ?? meta?.title ?? String(it.id ?? '');
    return cleanLabel(String(raw));
  };
  // Recursively clean labels; namespaces nest their own kind folders, so title-case
  // those too (functions → Functions) for consistency with the top level.
  const clean = (list: any[]): any[] =>
    (list ?? []).map(it =>
      it.type === 'category'
        ? { ...it, label: kindDisplay(it.label) ?? cleanLabel(String(it.label ?? '')), items: clean(it.items) }
        : { ...it, label: labelOf(it) }
    );

  const kindCats = items.filter(it => it.type === 'category');
  const topDocs = items.filter(it => it.type === 'doc');
  const indexItem = topDocs.find(d => /(^|\/)index$/.test(String(d.id))) ?? topDocs[0];
  const extraDocs = clean(topDocs.filter(d => d !== indexItem));

  let inner: any[];
  if (classifyPackage(name) === 'driver') {
    const nonClass: any[] = [];
    let classDocs: any[] = [];
    for (const cat of kindCats) {
      if (kindDisplay(cat.label) === 'Classes') {
        classDocs = clean(cat.items); // flatten driver classes to direct children
      } else {
        nonClass.push({
          ...cat,
          label: kindDisplay(cat.label) ?? cleanLabel(String(cat.label)),
          collapsed: true,
          items: clean(cat.items),
        });
      }
    }
    inner = [...sortByKindOrder(nonClass, DRIVER_NONCLASS_ORDER), ...classDocs, ...extraDocs];
  } else {
    const groups = kindCats.map(cat => ({
      ...cat,
      label: kindDisplay(cat.label) ?? cleanLabel(String(cat.label)),
      collapsed: false,
      items: clean(cat.items),
    }));
    inner = [...sortByKindOrder(groups, FRAMEWORK_KIND_ORDER), ...extraDocs];
  }

  // A package that generated nothing (e.g. its dist isn't built, so TypeDoc
  // resolved no exports) has no index and no kinds. Emitting a category with
  // neither items nor a link makes Docusaurus throw and take down the whole
  // dev server; drop it instead — it reappears once the package is built.
  if (!indexItem && inner.length === 0) {
    return null;
  }

  return {
    type: 'category',
    label: `@atomic-testing/${name}`,
    collapsed: true,
    ...(indexItem ? { link: { type: 'doc', id: indexItem.id } } : {}),
    items: inner,
  };
}

const config: Config = {
  title: 'Atomic Testing',
  tagline: 'Portable UI testing library: Simplify and unify across frameworks and libraries',
  favicon: 'img/favicon.ico',

  url: 'https://www.atomic-testing.dev',
  // Set the /<baseUrl>/ pathname under which your site is served
  // For GitHub pages deployment, it is often '/<projectName>/'
  baseUrl: '/',

  // GitHub pages deployment config.
  organizationName: 'atomic-testing', // Usually your GitHub org/user name.
  projectName: 'atomic-testing', // Usually your repo name.
  deploymentBranch: 'gh-pages', // Branch that GitHub pages will deploy from.

  onBrokenLinks: 'throw',

  trailingSlash: true,

  future: {
    faster: true, // Enable faster builds (renamed from experimental_faster in Docusaurus 3.10)
    v4: {
      removeLegacyPostBuildHeadAttribute: true,
    },
  },

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  markdown: {
    mermaid: true,
    hooks: {
      onBrokenMarkdownLinks: 'warn',
    },
  },

  themes: ['@docusaurus/theme-mermaid'],

  plugins: [
    [
      // https://github.com/tgreyuk/typedoc-plugin-markdown/tree/master/packages/docusaurus-plugin-typedoc
      'docusaurus-plugin-typedoc',

      // Plugin / TypeDoc options
      {
        entryPoints: [...getPackageEntryPoints()],
        entryPointStrategy: 'packages',
        tsconfig: '../tsconfig.json',
        sidebar: {},
        // Hide @internal-tagged exports (driver-package implementation details
        // like default option objects and ScenePart wiring constants) from the
        // generated reference — the tag alone does nothing without this flag.
        // Does NOT strip them from compiled output; docs-only, reversible.
        excludeInternal: true,
        // Suppress prepending the repo README (npm/CI badges) to the
        // project-level index.md TypeDoc's entryPointStrategy:'packages'
        // always writes at docs/api/index.md — that page still exists (a
        // flat "here are all 28 packages" list; 'none' only drops the README
        // content), which is why sidebars.ts gives its own curated,
        // framework/driver-split landing page a *different* slug
        // (/api-reference) rather than trying to reuse /api.
        readme: 'none',
        // Emit each package directly under api/ (e.g. api/core) instead of
        // nesting it under an api/@atomic-testing/ scope directory. This drops
        // the redundant "@atomic-testing" grouping layer from the API sidebar
        // while each package keeps its full "@atomic-testing/…" label (derived
        // from the generated index page title). See sidebars.ts → API Reference.
        excludeScopesInPaths: true,
        // Partition each class/interface page's members into own / inherited /
        // protected sections (see typedoc/partition-members-plugin.mjs). Absolute
        // path because TypeDoc resolves relative plugin specifiers from its own
        // node_modules location, not from here.
        plugin: [path.join(__dirname, 'typedoc', 'partition-members-plugin.mjs')],
        theme: 'markdown-partitioned',
      },
    ],
    sidebarWidthInitPlugin,
  ],

  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      {
        docs: {
          sidebarPath: require.resolve('./sidebars.ts'),
          sidebarItemsGenerator: async ({ defaultSidebarItemsGenerator, ...args }) => {
            const items = await defaultSidebarItemsGenerator(args);
            // Only the per-package `api/<name>` autogenerated blocks get reshaped
            // into a collapsed package category; every other block (guides,
            // advanced-concepts) passes through untouched.
            const dirName = (args as { item?: { dirName?: string } }).item?.dirName;
            const name = typeof dirName === 'string' ? dirName.match(/^api\/(.+)$/)?.[1] : undefined;
            if (name) {
              const shaped = shapeApiPackage(name, items, (args as { docs?: any[] }).docs ?? []);
              return shaped ? [shaped] : [];
            }
            return items;
          },
          // Please change this to your repo.
          // Remove this to remove the "edit this page" links.
          //
          // The `api/` subtree is generated by docusaurus-plugin-typedoc at build time
          // and is gitignored (see /.gitignore) — there's no source file in the repo for
          // "Edit this page" to link to, so suppress the link there by returning
          // `undefined` (per EditUrlFunction in @docusaurus/plugin-content-docs) instead
          // of building a URL to a path that 404s.
          editUrl: ({ docPath }) =>
            docPath.startsWith('api/') || docPath.startsWith('api\\')
              ? undefined
              : `https://github.com/atomic-testing/atomic-testing/tree/main/docs/docs/${docPath}`,
        },
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    // Replace with your project's social card
    image: 'img/social-card.png',
    navbar: {
      title: 'Atomic Testing',
      logo: {
        alt: 'Atomic Testing Logo',
        src: 'img/logo-atom.svg',
      },
      items: [
        {
          type: 'doc',
          docId: 'quick-start',
          position: 'left',
          label: 'Getting Started',
        },
        {
          // The evaluator track's generated index (see the "Evaluating Atomic
          // Testing" category in sidebars.ts) — evidence pages for the people
          // deciding whether a team adopts, not the IC already trying it.
          to: '/docs/evaluate',
          position: 'left',
          label: 'Why adopt',
        },
        {
          type: 'doc',
          docId: 'concepts',
          position: 'left',
          label: 'Core Concepts',
        },
        {
          // Surfaces the scaffolder's verified/experimental support tiers — the
          // one page a reader checks before running `create atomic-testing`.
          to: '/docs/support-matrix',
          position: 'left',
          label: 'Support matrix',
        },
        {
          // Points at the API Reference category's generated index (see
          // sidebars.ts) rather than a docId: the category has no single
          // hand-authored landing doc, so a plain path avoids depending on
          // Docusaurus's internal id scheme for generated-index pages.
          to: '/docs/api-reference/',
          position: 'left',
          label: 'API',
        },
        {
          href: 'https://github.com/atomic-testing/atomic-testing',
          label: 'GitHub',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Docs',
          items: [
            {
              label: 'Getting started',
              to: '/docs/quick-start',
            },
            {
              label: 'Why Atomic Testing?',
              to: '/docs/why-atomic-testing',
            },
            {
              label: 'Evaluating Atomic Testing',
              to: '/docs/evaluate',
            },
            {
              label: 'Package Guide',
              to: '/docs/framework-guide',
            },
            {
              label: 'Core Concepts',
              to: '/docs/concepts',
            },
            {
              label: 'Best practices',
              to: '/docs/best-practices',
            },
            {
              label: 'API reference',
              to: '/docs/api-reference/',
            },
          ],
        },
        {
          title: 'Community',
          items: [
            {
              label: 'Discord',
              href: 'https://discord.gg/qbeqWTYzEH',
            },
            {
              label: 'Twitter/X',
              href: 'https://twitter.com/TestingAtomic',
            },
          ],
        },
        {
          title: 'More',
          items: [
            {
              label: 'FAQ',
              to: '/docs/faq',
            },
            {
              label: 'GitHub',
              href: 'https://github.com/atomic-testing/atomic-testing',
            },
          ],
        },
      ],
      copyright: `Copyright © 2022-${new Date().getFullYear()} Tangent Lin`,
    },
    prism: {
      theme: atomicCodeTheme,
      darkTheme: atomicCodeTheme,
    },
    colorMode: {
      defaultMode: 'light',
      disableSwitch: false,
      respectPrefersColorScheme: true,
    },
    // @see https://docusaurus.io/docs/search
    algolia: {
      appId: 'HKBV6KED15',
      apiKey: '31786977c036097aab45afff518ca641',
      indexName: 'atomic-testing',
      contextualSearch: false,
      replaceSearchResultPathname: {
        from: '/docs/', // or as RegExp: /\/docs\//
        to: '/docs/',
      },
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
