/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars = {
  // New organized sidebar structure focused on user journey
  tutorialSidebar: [
    // GETTING STARTED (Most Important)
    {
      type: 'category',
      label: '🚀 Getting Started',
      collapsed: false,
      items: [
        'quick-start', // NEW: Choose your framework + 5-minute example
        'framework-guide', // NEW: React vs Vue vs Playwright decision guide
        'setup-wizard', // NEW: Interactive package selector
        'why-atomic-testing', // NEW: Long-term value demonstration
        'tutorial', // EXISTING: Detailed tutorial
      ],
    },

    // CORE CONCEPTS (Educational)
    {
      type: 'category',
      label: '🧠 Core Concepts',
      collapsed: true,
      items: [
        'intro', // EXISTING: Introduction (moved here)
        'concepts', // EXISTING: Component drivers, locators, etc.
        'setup', // EXISTING: Step-by-step setup
      ],
    },

    // PRACTICAL GUIDES
    {
      type: 'category',
      label: '💼 Practical Guides',
      collapsed: true,
      items: [
        'best-practices', // EXISTING
        'cheat-sheets', // EXISTING
      ],
    },

    // ADVANCED
    {
      type: 'category',
      label: '🔧 Advanced',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Advanced Concepts',
          items: [{ type: 'autogenerated', dirName: 'advanced-concepts' }],
        },
        'faq', // EXISTING
      ],
    },

    // REFERENCE
    {
      type: 'category',
      label: '📖 API Reference',
      collapsed: true,
      items: [
        'api-overview', // EXISTING
        {
          type: 'category',
          label: 'API Documentation',
          items: [{ type: 'autogenerated', dirName: 'api' }],
        },
      ],
    },
  ],
} satisfies SidebarsConfig;

module.exports = sidebars;
