/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

import { getBucketedDocPackages } from './scripts/docPackages.mjs';

// See docs/scripts/docPackages.mjs for the framework/driver classification
// rule and why it must be read from packages/ (not the generated docs/api/
// output, which doesn't exist yet when this file is evaluated).
const { driver: driverPackages, framework: frameworkPackages } = getBucketedDocPackages();

const sidebars = {
  // New organized sidebar structure focused on user journey
  tutorialSidebar: [
    // GETTING STARTED (Most Important)
    {
      type: 'category',
      label: '🚀 Getting Started',
      collapsed: false,
      items: [
        'quick-start', // NEW: Choose your framework + 5-minute example
        'setup', // EXISTING: Runner config + step-by-step setup (must precede tutorial)
        'framework-guide', // NEW: React vs Vue vs Playwright decision guide
        'tutorial', // EXISTING: Detailed tutorial
        'why-atomic-testing', // NEW: Long-term value demonstration — after the hands-on path, not interrupting it
      ],
    },

    // CORE CONCEPTS (Educational)
    {
      type: 'category',
      label: '🧠 Core Concepts',
      collapsed: true,
      items: [
        'intro', // EXISTING: Introduction (moved here)
        'concepts', // EXISTING: Component drivers, locators, etc.
      ],
    },

    // PRACTICAL GUIDES
    {
      type: 'category',
      label: '💼 Practical Guides',
      collapsed: true,
      items: [
        'best-practices', // EXISTING
        'cheat-sheets', // EXISTING
        'faq', // MOVED from Advanced — quick-reference, not expert content
        {
          type: 'category',
          label: 'Guides',
          items: [{ type: 'autogenerated', dirName: 'guides' }],
        },
      ],
    },

    // ADVANCED
    {
      type: 'category',
      label: '🔧 Advanced',
      collapsed: true,
      // The advanced-concepts docs sit directly under Advanced — there is only
      // one group of them, so an intermediate "Advanced Concepts" category would
      // be a redundant nesting layer.
      items: [{ type: 'autogenerated', dirName: 'advanced-concepts' }],
    },

    // REFERENCE
    // Split into two categories mirroring how these packages actually read:
    // Framework & Interactor packages are thin wiring (~1 Interactor class +
    // a handful of functions/types) around one environment; Component Driver
    // packages are a per-component vocabulary of 10-80+ driver classes. See
    // issue #1088.
    {
      type: 'category',
      label: '📖 API Reference',
      collapsed: true,
      // No custom `link` here: TypeDoc's entryPointStrategy:'packages' already
      // emits a project-level docs/api/index.md (the repo README) that claims
      // the /docs/api/ route natively — a generated-index at the same slug
      // collides with it ("Duplicate routes found"). That native page is what
      // navbar/footer "API" links point at.
      items: [
        {
          type: 'category',
          label: 'Framework & Interactor APIs',
          link: {
            type: 'generated-index',
            title: 'Framework & Interactor APIs',
            description:
              'One package per test environment (React, Vue, Angular, Playwright, Storybook) plus the core/dom-core abstractions they all build on — thin wiring around the Interactor interface.',
            slug: '/api/framework-interactor',
          },
          items: frameworkPackages.map(name => ({ type: 'autogenerated', dirName: `api/${name}` })),
        },
        {
          type: 'category',
          label: 'Component Driver APIs',
          link: {
            type: 'generated-index',
            title: 'Component Driver APIs',
            description:
              'One package per UI component library (HTML, MUI, Angular Material, Astryx, Radix, PrimeVue, shadcn/ui) — each a vocabulary of driver classes for that library’s components.',
            slug: '/api/component-drivers',
          },
          items: driverPackages.map(name => ({ type: 'autogenerated', dirName: `api/${name}` })),
        },
      ],
    },
  ],
} satisfies SidebarsConfig;

module.exports = sidebars;
