/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

import { getBucketedDocPackages } from './scripts/docPackages.mjs';

// See docs/scripts/docPackages.mjs for the framework/driver classification
// rule and why it must be read from packages/ (not the generated docs/api/
// output, which doesn't exist yet when this file is evaluated).
const { driver: driverPackages, framework: frameworkPackages } = getBucketedDocPackages();

const sidebars = {
  // Sidebar structure follows the reader's journey: get started → evaluate (the
  // decision-maker's evidence track) → pick packages → learn the concepts →
  // apply recipes → go deep → reference.
  tutorialSidebar: [
    // GETTING STARTED — the linear path only. Package-selection and the support
    // matrix are decision aids, not sequential steps, so they live in their own
    // "Choosing Packages" group below rather than interrupting this flow.
    {
      type: 'category',
      label: '🚀 Getting Started',
      collapsed: false,
      items: [
        'why-atomic-testing', // The consolidated "why" — problem, solution, and the ROI case (absorbs the former Introduction)
        'quick-start', // `create atomic-testing` one-liner + 5-minute example
        'setup', // Runner config + step-by-step setup (must precede tutorial)
        'tutorial', // Detailed tutorial
      ],
    },

    // EVALUATING — evidence pages for the people deciding whether a team adopts
    // (managers, staff/platform owners, directors), not the IC already trying it.
    // Kept out of Getting Started so the linear path stays linear: these are
    // diligence reading, not sequential steps.
    {
      type: 'category',
      label: '🔍 Evaluating Atomic Testing',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'Evaluating Atomic Testing',
        description:
          'Evidence for the people deciding whether a team adopts: proof of portability, the API stability and EOL policy, runnable example apps, a rollout playbook, agent-native testing skills, and governance & risk.',
        slug: '/evaluate',
      },
      items: [
        'evaluate/proof-of-portability', // The cross-runtime conformance evidence behind "write once, run anywhere"
        'evaluate/api-stability', // Versioning, deprecation & EOL policy — what pre-1.0 means here
        'evaluate/example-apps', // Runnable example apps to inspect before committing
        'evaluate/adoption-rollout', // Incremental rollout playbook for teams and orgs
        'evaluate/testing-with-ai-agents', // Agent-native skills that write and maintain driver tests
        'evaluate/governance', // Maintainership, risk disclosure, and how change is managed
      ],
    },

    // CHOOSING PACKAGES — decision aids for the hand-install path. Grouped
    // together because a reader consults them to decide, not to follow in order.
    {
      type: 'category',
      label: '📦 Choosing Packages',
      collapsed: true,
      items: [
        'framework-guide', // Package Guide: which driver/framework packages to install for your stack
        'support-matrix', // Which framework × runner × design-system combos are verified vs. experimental
        'manual-installation', // Escape hatch from the scaffolder: wire the packages up by hand
      ],
    },

    // CORE CONCEPTS (Educational)
    {
      type: 'category',
      label: '🧠 Core Concepts',
      collapsed: true,
      items: [
        'concepts', // Component drivers, locators, ScenePart, TestEngine
      ],
    },

    // PRACTICAL GUIDES
    {
      type: 'category',
      label: '💼 Practical Guides',
      collapsed: true,
      items: [
        'best-practices', // EXISTING
        'cheat-sheets', // EXISTING
        'faq', // MOVED from Advanced — quick-reference, not expert content
        {
          type: 'category',
          label: 'Guides',
          items: [{ type: 'autogenerated', dirName: 'guides' }],
        },
      ],
    },

    // ADVANCED
    {
      type: 'category',
      label: '🔧 Advanced',
      collapsed: true,
      // The advanced-concepts docs sit directly under Advanced — there is only
      // one group of them, so an intermediate "Advanced Concepts" category would
      // be a redundant nesting layer.
      items: [{ type: 'autogenerated', dirName: 'advanced-concepts' }],
    },

    // DRIVER COVERAGE — reference tables of which components each design-system
    // driver package covers. Kept out of "Guides" (which is task recipes) because
    // this is lookup data, not a walkthrough.
    {
      type: 'category',
      label: '📊 Driver Coverage',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'driver-coverage' }],
    },

    // REFERENCE
    // Split into two categories mirroring how these packages actually read:
    // Framework & Interactor packages are thin wiring (~1 Interactor class +
    // a handful of functions/types) around one environment; Component Driver
    // packages are a per-component vocabulary of 10-80+ driver classes. See
    // issue #1088.
    {
      type: 'category',
      label: '📖 API Reference',
      collapsed: true,
      // Slug is /api-reference, NOT /api: TypeDoc's entryPointStrategy:'packages'
      // always writes its own project-level docs/api/index.md (a flat "here are
      // all 28 packages" list — readme:'none' in docusaurus.config.ts only
      // suppresses prepending the repo README to it, it still exists), so a
      // generated-index at /api collides with it ("Duplicate routes found").
      // Using a different slug avoids the collision entirely; navbar/footer
      // "API" links point at this richer, framework/driver-split page instead
      // of TypeDoc's flat one.
      link: {
        type: 'generated-index',
        title: 'API Reference',
        description:
          'Generated API documentation for every @atomic-testing/* package, split by framework/interactor wiring vs. component driver vocabulary.',
        slug: '/api-reference',
      },
      items: [
        {
          type: 'category',
          label: 'Framework & Interactor APIs',
          link: {
            type: 'generated-index',
            title: 'Framework & Interactor APIs',
            description:
              'One package per test environment (React, Vue, Angular, Playwright, Storybook) plus the core/dom-core abstractions they all build on — thin wiring around the Interactor interface.',
            slug: '/api/framework-interactor',
          },
          items: frameworkPackages.map(name => ({ type: 'autogenerated', dirName: `api/${name}` })),
        },
        {
          type: 'category',
          label: 'Component Driver APIs',
          link: {
            type: 'generated-index',
            title: 'Component Driver APIs',
            description:
              'One package per UI component library (HTML, MUI, Angular Material, Astryx, Radix, PrimeVue, shadcn/ui) — each a vocabulary of driver classes for that library’s components.',
            slug: '/api/component-drivers',
          },
          items: driverPackages.map(name => ({ type: 'autogenerated', dirName: `api/${name}` })),
        },
      ],
    },
  ],
} satisfies SidebarsConfig;

module.exports = sidebars;
