name: Verify pull request

on:
  pull_request:
  merge_group:
    branches: ['main']
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Build once - this job builds all packages and caches the results
  build:
    name: Build packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup with build
        uses: ./.github/actions/builderui-setup

      - name: Cache built packages
        uses: actions/cache@v4
        with:
          path: |
            packages/*/build
            packages/*/dist
          key: build-packages-${{ github.sha }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-packages
          path: |
            packages/*/build
            packages/*/dist
          retention-days: 1

  # Lint and type-check jobs that need built packages
  lint:
    name: Linting and formatting
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dependencies only
        uses: ./.github/actions/deps-setup

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: built-packages
          path: packages

      - name: Run code formatter
        run: pnpm check:style

      - name: Run linter
        run: pnpm check:lint

  type-check:
    name: Type checking
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dependencies only
        uses: ./.github/actions/deps-setup

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: built-packages
          path: packages

      - name: Run type checker
        run: pnpm check:type

  # Test matrix for component drivers
  component-driver-tests:
    name: Test ${{ matrix.name }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'HTML components'
            directory: 'component-driver-html-test'
          - name: 'MUI v5 components'
            directory: 'component-driver-mui-v5-test'
          - name: 'MUI v6 components'
            directory: 'component-driver-mui-v6-test'
          - name: 'MUI v7 components'
            directory: 'component-driver-mui-v7-test'
          - name: 'MUI X v5 components'
            directory: 'component-driver-mui-x-v5-test'
          - name: 'MUI X v6 components'
            directory: 'component-driver-mui-x-v6-test'
          - name: 'MUI X v7 components'
            directory: 'component-driver-mui-x-v7-test'
          - name: 'MUI X v8 components'
            directory: 'component-driver-mui-x-v8-test'
          - name: 'Vue 3 components'
            directory: 'vue-3-test'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dependencies only
        uses: ./.github/actions/deps-setup

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: built-packages
          path: packages

      - name: Run test
        run: pnpm test:dom
        working-directory: ./package-tests/${{ matrix.directory }}

  # Example test (separate since it has different setup)
  example-mui-signup-form-test:
    name: Test example MUI signup form
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: PNPM Setup
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Install dependencies
        run: pnpm install .
        working-directory: ./examples/example-mui-signup-form

      - name: Run dom test
        run: pnpm test:dom
        working-directory: ./examples/example-mui-signup-form
