name: Verify pull request

on:
  pull_request:
  merge_group:
    branches: ['main']
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: linting and formatting
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/builderui-setup

      - name: Run code formatter
        run: pnpm check:style

      - name: Run linter
        run: pnpm check:lint

  type-check:
    name: type checking
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/builderui-setup

      - name: Run type checker
        run: pnpm check:type

  component-driver-html-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/builderui-setup

      - name: Run test
        run: pnpm test:dom
        working-directory: ./packages/component-driver-html-test

  component-driver-mui-v5-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/builderui-setup

      - name: Run test
        run: pnpm test:dom
        working-directory: ./packages/component-driver-mui-v5-test

  component-driver-mui-v6-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/builderui-setup

      - name: Run test
        run: pnpm test:dom
        working-directory: ./packages/component-driver-mui-v6-test

  component-driver-mui-v7-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/builderui-setup

      - name: Run test
        run: pnpm test:dom
        working-directory: ./packages/component-driver-mui-v7-test

  component-driver-mui-x-v5-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/builderui-setup

      - name: Run test
        run: pnpm test:dom
        working-directory: ./packages/component-driver-mui-x-v5-test

  component-driver-mui-x-v6-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/builderui-setup

      - name: Run test
        run: pnpm test:dom
        working-directory: ./packages/component-driver-mui-x-v6-test

  component-driver-mui-x-v7-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/builderui-setup

      - name: Run test
        run: pnpm test:dom
        working-directory: ./packages/component-driver-mui-x-v7-test

  component-driver-mui-x-v8-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/builderui-setup

      - name: Run test
        run: pnpm test:dom
        working-directory: ./packages/component-driver-mui-x-v8-test

  vue-3-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/builderui-setup

      - name: Run test
        run: pnpm test:dom
        working-directory: ./packages/vue3-test

  example-mui-signup-form-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: PNPM Setup
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Install dependencies
        run: pnpm install .
        working-directory: ./examples/example-mui-signup-form

      - name: Run dom test
        run: pnpm test:dom
        working-directory: ./examples/example-mui-signup-form
