name: Verify pull request

on:
  pull_request:
  merge_group:
    branches: ['main']
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/builderui-setup

      - name: Run linter
        run: pnpm lint

      # TODO: Add build step, build is more complicated because it involves building the Kotlin core and the UI

  component-driver-html-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/builderui-setup

      - name: Run test
        run: pnpm test:dom
        working-directory: ./packages/component-driver-html-test

  component-driver-mui-v5-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/builderui-setup

      - name: Run MUI V5 test
        run: pnpm test:dom
        working-directory: ./packages/component-driver-mui-v5-test

  component-driver-mui-v6-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/builderui-setup

      - name: Run MUI V5 test
        run: pnpm test:dom
        working-directory: ./packages/component-driver-mui-v6-test

  component-driver-mui-x-v7-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/builderui-setup

      - name: Run MUI V5 test
        run: pnpm test:dom
        working-directory: ./packages/component-driver-mui-x-v7-test
    
