name: Verify pull request

on:
  pull_request:
  merge_group:
    branches: ['main']
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Auto-format code and commit if needed
  auto-format:
    name: Auto-format code
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    outputs:
      changes_made: ${{ steps.check_changes.outputs.changes_made }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup dependencies only
        uses: ./.github/actions/deps-setup

      - name: Run code formatter
        run: pnpm check:style

      - name: Check for changes
        id: check_changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "changes_made=true" >> $GITHUB_OUTPUT
          else
            echo "changes_made=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit formatting changes
        if: steps.check_changes.outputs.changes_made == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "style: auto-format code with prettier
          git push origin HEAD:${{ github.head_ref || github.ref_name }}

  # Build once - this job builds all packages and caches the results
  build:
    name: Build packages
    runs-on: ubuntu-latest
    needs: auto-format
    if: needs.auto-format.outputs.changes_made == 'false'
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup with build
        uses: ./.github/actions/builderui-setup

      - name: Cache built packages
        uses: actions/cache@v4
        with:
          path: |
            packages/*/build
            packages/*/dist
          key: build-packages-${{ github.sha }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-packages
          path: |
            packages/*/build
            packages/*/dist
          retention-days: 1

  # Lint and type-check jobs that need built packages
  lint:
    name: Linting and formatting
    runs-on: ubuntu-latest
    needs: [auto-format, build]
    if: needs.auto-format.outputs.changes_made == 'false'
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dependencies only
        uses: ./.github/actions/deps-setup

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: built-packages
          path: packages

      - name: Run code formatter
        run: pnpm check:style

      - name: Run linter
        run: pnpm check:lint

  type-check:
    name: Type checking
    runs-on: ubuntu-latest
    needs: [auto-format, build]
    if: needs.auto-format.outputs.changes_made == 'false'
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dependencies only
        uses: ./.github/actions/deps-setup

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: built-packages
          path: packages

      - name: Run type checker
        run: pnpm check:type

  # Test matrix for component drivers
  component-driver-tests:
    name: Test ${{ matrix.name }}
    runs-on: ubuntu-latest
    needs: [auto-format, build]
    if: needs.auto-format.outputs.changes_made == 'false'
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'HTML components'
            directory: 'component-driver-html-test'
          - name: 'MUI v5 components'
            directory: 'component-driver-mui-v5-test'
          - name: 'MUI v6 components'
            directory: 'component-driver-mui-v6-test'
          - name: 'MUI v7 components'
            directory: 'component-driver-mui-v7-test'
          - name: 'MUI X v5 components'
            directory: 'component-driver-mui-x-v5-test'
          - name: 'MUI X v6 components'
            directory: 'component-driver-mui-x-v6-test'
          - name: 'MUI X v7 components'
            directory: 'component-driver-mui-x-v7-test'
          - name: 'MUI X v8 components'
            directory: 'component-driver-mui-x-v8-test'
          - name: 'Vue 3 components'
            directory: 'vue-3-test'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dependencies only
        uses: ./.github/actions/deps-setup

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: built-packages
          path: packages

      - name: Run test
        run: pnpm test:dom
        working-directory: ./package-tests/${{ matrix.directory }}

  # Example test (separate since it has different setup)
  example-mui-signup-form-test:
    name: Test example MUI signup form
    runs-on: ubuntu-latest
    needs: auto-format
    if: needs.auto-format.outputs.changes_made == 'false'
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: PNPM Setup
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Install dependencies
        run: pnpm install .
        working-directory: ./examples/example-mui-signup-form

      - name: Run dom test
        run: pnpm test:dom
        working-directory: ./examples/example-mui-signup-form
