name: Documentation CI

on:
  pull_request:
    paths:
      - 'docs/**'

jobs:
  deploy:
    name: Verify documentation build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup dependencies only
        uses: ./.github/actions/deps-setup

      - name: Build packages
        run: ./publish.sh --build-only

      - name: Install documentation dependencies
        run: pnpm install .
        working-directory: ./docs

      - name: Verify documentation build
        run: pnpm build
        working-directory: ./docs
